---
# config.yaml
# 
# Config info for pipeline that takes selected keyframes and train + evaluate models
# All paths are relative to the project directory
#
# Variables
# camera_path: path to the camera paths for evaluation
# eval_images: path to the eval_image dataset
# experiments: list of experiment names. Nerf experiments should end w/ nerf and Gsplats end w/ splat
# full_transforms: path to the complete set of colmap transforms for both the eval and training images
# kf_num_files: dictionary mapping each experiment (name) to the corresponding txt file with keyframe numbers
# models: name of models directory
# processed: name of directories containing the processed data
# proj_dir: absolute path of the project. All other paths here should be relative to this path
# renders: path to the renders directory
# repo: path to the github repository
# results: path to the directory with results

camera_path: Drone-Mapping/transforms/camera_paths/eval_path.json
eval_images: data/lake_lag/processed/eval
experiments:
  - 70p_content_nerf
full_transforms: Drone-Mapping/transforms/lake_lag/full_transforms.json
kf_num_files:
  10p_uniform_test3_nerf: 10p_uniform.txt
kf_nums_dir: Drone-Mapping/pipeline/kf_nums/
models: models/
processed: data/lake_lag/tmp_test_data/
proj_dir: /home/navlab/NeRF/drone_mapping/
renders: renders/
repo: Drone-Mapping/
results: results/