#!/usr/bin/env python3
"""
Python code to export parameters in config.yaml to bash script
Note that bash scripts generated by this code do not have executable permission
Use source command to run the generated bash script
"""

import yaml


def export_to_bash(yaml_file):
    with open(yaml_file, "r") as f:
        data = yaml.safe_load(f)

    bash_script = "#!/bin/bash\n"
    for key, value in data.items():
        if isinstance(value, list):
            bash_script += f"declare -a {key}\n"
            for i, item in enumerate(value):
                bash_script += f'{key}[{i}]="{item}"\n'
        else:
            bash_script += f'{key}="{value}"\n'

    with open("config.bash", "w") as f:
        f.write(bash_script)

    print("Bash script generated: config.bash")
    print("Source this script in your Bash session to export the variables.")


if __name__ == "__main__":
    yaml_file = "config.yaml"  # Replace with your YAML file path
    export_to_bash(yaml_file)
